name = "contentful-next-esr-demo"
main = "src/index.ts"
account_id = "37899b450014da109f58073d3134d8a4"
usage_model = "bundled"
compatibility_date = "2022-04-27"
minify = true
route = "https://contentful-next-esr-demo.ninetailed.io/*"

[vars]
NINETAILED_API_KEY = 'b4b2fa59-1199-4942-8a87-f6228272a26a'
NINETAILED_ENVIRONMENT = 'main'
CONTENTFUL_SPACE_ID = '0au1p5a77y87'
CONTENTFUL_ENVIRONMENT_ID = 'master'
CONTENTFUL_ACCESS_TOKEN = 'H_6sFABJ99WYy-H90Z38URIbuYhqYjlw_TjR2J4jH2c'